spring:
  application:
    name: springSecurityDemo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_security_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  data:
    redis:
      host: 192.168.249.130
      port: 6379
      password: 1234
      database: 0
      timeout: 3000




